### ISSUE TITLE
Add devcontainer

### ISSUE THREAD

**Issue by alexallmont** [datasig-ac-uk/RoughPy#148]
Having recently joining the project, I set up my development environment and hit some issues on MacOS. I switched to Linux and then found a few dependencies and paths had to be set. I have captured this info in a `Dockerfile` and `devcontainer.json` which detail the tools anyone will need to spin up a containerised VSCode dev environment. This includes an example `launch.json` for debugging C++ and python tests (and additionally debugging C++ launched from python). After getting the Linux dev environment working, I had to make a few more to get it working on MacOS too.

This ticket is for tracking my changes for consideration for a PR if it's something you would like to make available to other developers. 

(A nice side-effect of these changes is they allow you to run the IDE online through a GitHub codespace too, which can be a very helpful tool for teaching and demonstration)

**Comment by inakleinbottle** [comment]
Good idea. I also encountered a problem debugging on MacOs because using the debugger requires the binary to be signed with the correct entitlements (who knows why debug builds are not automatically constructed in this way).

It might well be worth having several containers defined in the project directory to help people test/debug on the different platforms. 

Cross compiling is something that we might eventually need to support in the build system, such as building for Raspberry Pi and other embedded platforms. I don't know how to do this at the moment, but things like this will definitely help.
