### ISSUE TITLE
Partition intermediates can be outside of the Interval that the Partition is defined on

### ISSUE THREAD

**Issue by lingyiyang** [datasig-ac-uk/RoughPy#80]
When constructing a Partition object, we have as arguments an Interval and a list of intermediate points. However, this constructor does not seem to check whether these intermediate points are within the interval. 
For example:
```python
partition = rp.Partition(rp.RealInterval(0.,1.), intermediates=np.arange(10))
print(partition.intermediates())
```
returns
```
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
```
Expected behaviour should be either to silently remove the points outside of the Interval or have a warning that the Interval does not contain all intermediate points.

**Comment by terrylyons** [comment]
It is intended to give the partition of the interval using the unsorted set of points. The points do not have to be contained in the interval.

On 22 Feb 2024, at 11:18, lingyiyang ***@***.***> wrote:

﻿

When constructing a Partition object, we have as arguments an Interval and a list of intermediate points. However, this constructor does not seem to check whether these intermediate points are within the interval.
For example:

partition = rp.Partition(rp.RealInterval(0.,1.), intermediates=np.arange(10))
print(partition.intermediates())

returns

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


Expected behaviour should be either to silently remove the points outside of the Interval or have a warning that the Interval does not contain all intermediate points.

**Comment by inakleinbottle** [comment]
So something is strange here and requires more than a superficial fix. The constructor for a partition is as follows:
```c++
Partition::Partition(RealInterval base, Slice<param_t> intermediate_points)
    : RealInterval(std::move(base))
{
    m_intermediate_points.reserve(intermediate_points.size());
    for (auto&& mid : intermediate_points) {
        if (contains_point(mid) && mid != inf() && mid != sup()) {
            m_intermediate_points.push_back(mid);
        }
    }
    std::sort(m_intermediate_points.begin(), m_intermediate_points.end());
}
```
I suspect this means there is a bug with "contains", but I will have to investigate.

**Comment by inakleinbottle** [comment]
Ok, so the problem is that the above constructor is not used from the Python interface, instead the interface constructs vector of intermediates separately and then uses a move constructor to populate the partition. This move constructor does not do any checking or sorting.
